config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :notes

  authenticated :user do
    root to: 'notes#index'
  end

  root to: 'welcome#index'



  get "/notes", to: "notes#index"

  get "notes/new", to: "notes#new"

  post "notes", to: "notes#create"

  get "notes/:id", to: "notes#show"

  get "notes/:id/edit", to: "notes#edit"

  patch "/notes/:id", to: "notes#update"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :authentication_keys => [:email]

  has_many :notes, dependent: :destroy

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :find_note, only: [:show, :edit, :update, :destroy]


  def index
    @notes = Note.where(user_id: current_user)
  end


  def new
    @note = current_user.notes.build
  end

  def create
    @note = current_user.notes.build(note_params)

    if @note.save
      redirect_to notes_url
    else
      puts "ERROR test to see if we are getting here on create"
    end

  end

  def show
    @note = Note.find(params[:id])
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy

    redirect_to notes_path

  end

  private

  def find_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :content, :user_id)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Jot-It Notes | All your thoughts in one app

  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %header
    .header_inner
      = link_to image_tag('jotit_logo.png'), root_path

      %nav
        - if user_signed_in?
          = link_to "New Note", new_note_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          = link_to "Log In", new_user_session_path

    %p.notice= notice
    %p.alert= alert

    = yield

  %footer

app/views/notes/_form.html.haml
#note_show

  = simple_form_for @note do |f|
    = f.input_field :title, :placeholder => "Note title"
    = f.input_field :content, :placeholder => "Jot your note"

    <br>

    = f.button :submit 

app/views/notes/edit.html.haml
#notes

  %h1 Edit Your Note

  = render 'form'

  %button= link_to "Cancel", note_path

app/views/notes/index.html.haml
.wrapper_with_padding
  #note.clearfix
    - unless @notes.blank?
      - @notes.each do |note|
        %a{href: (url_for [note])}
          .note
            %p.title= note.title
            %p.date= time_ago_in_words(note.created_at)
    - else
      %h2 Add a -# NOTE:
      %p It appears you haven't created any notes yet... create a new note below.
      %button= link_to "New Note", new_note_path

app/views/notes/new.html.haml
#notes

  %h1 Add a new Note

  = render 'form'

app/views/notes/show.html.haml
#notes

  %h1= @note.title
  %p= @note.content

  %button=  link_to "All Notes", notes_path

  %button=  link_to "Edit", edit_note_path(@note)

  %button=  link_to "Delete", note_path(@note), method: :delete, data: {confirm: "Are you sure you want to delete?"}

app/views/users/sign_in.html.erb
<h2>Sign in</h2>

<%= form_tag("/sign_in", method: "post") do %>

<% end %>

app/views/users/sign_up.html.erb
<h2>Sign up</h2>

<%= form_tag("/sign_up", method: "post") do %>

<% end %>

app/views/welcome/index.html.erb
<h1> Welcome to Jot-it </h1>

<div>
<p> Welcome to Jot-It, a lightweight note-taking app that will save you time when jotting down your thoughts. </p>
</div>

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 Welcome to Jot-it
    %p Save time when jotting down your thoughts.
    %button= link_to "Get Started", new_user_registration_path